# Generated by Django 4.2.13 on 2024-06-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profileuser_options_alter_profileuser_managers_and_more"),
    ]

    operations = []
