# Generated by Django 4.2.13 on 2024-06-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_list_genre_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='genre_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
