# Generated by Django 4.2.13 on 2024-06-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_list_genre_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_list',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
    ]
