# Generated by Django 4.2.13 on 2024-06-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_list_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='image',
            field=models.ImageField(upload_to='book_images/'),
        ),
        migrations.CreateModel(
            name='ReviewsBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_books', to='books.book_list')),
            ],
        ),
    ]
